general:
  remote_storage: none
  max_file_size: 10000000000 # 10 GB
  disable_progress_bar: false
  backups_to_keep_local: 7
  log_level: info
  backups_to_keep_remote: 0

clickhouse:
  host: clickhouse
  port: 9000
  username: admin
  database: default
