name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Load mock environment variables
        run: |
          cp .env.production.example ./selfhost/.env.build

      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: selfhost_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/betterlytics-selfhost

      - name: Building selfhost image
        uses: docker/build-push-action@v6
        with:
          context: ./selfhost
          push: true
          tags: ${{ steps.selfhost_meta.outputs.tags }}
          labels: ${{ steps.selfhost_meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/betterlytics-selfhost:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/betterlytics-selfhost:buildcache,mode=max
